spring.application.name=automated-test-framework
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/test_framework
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
